#ifndef _NTFA_FALCON_CLIENT_CLIENT_STATUS_H_
#define _NTFA_FALCON_CLIENT_CLIENT_STATUS_H_
const uint32_t DOWN_FROM_REMOTE = 0;
const uint32_t KILLED_BY_REMOTE = 1;
const uint32_t REMOTE_WOULD_KILL = 2;
const uint32_t REMOTE_ERROR = 3;
const uint32_t UNKNOWN_ERROR = 4;
const uint32_t FALCON_E2E_TIMEOUT = 5;
const uint32_t KILL_LONG_DEAD = 6; 
const uint32_t REGISTRATION_ERROR = 7;
const uint32_t SIGN_OF_LIFE = 8;
#endif  //_NTFA_FALCON_CLIENT_CLIENT_STATUS_H_
