#ifndef _NTFA_ENFORCER_STATUS_H_
#define _NTFA_ENFORCER_STATUS_H_

enum spy_status {
    FALCON_SUCCESS = 0,
    FALCON_UNKNOWN_TARGET = 1,
    FALCON_BAD_GEN_VEC = 2,
    FALCON_FUTURE_GEN = 3,
    FALCON_LONG_DEAD = 4,
    FALCON_REGISTER_ACK = 5,
    FALCON_CANCEL_ACK = 6,
    FALCON_CANCEL_ERROR = 7,
    FALCON_KILL_ACK = 8,
    FALCON_GEN_RESP = 9,
    FALCON_UP = 10,
    FALCON_DOWN = 11,
    FALCON_UNKNOWN_ERROR = 12
};
#endif  // _NTFA_ENFORCER_STATUS_H_
